apiVersion: v1
kind: Secret
metadata:
  name: afrimart-secrets
  namespace: production
type: Opaque
stringData:
  # Database connection
  # Format: postgresql://username:password@endpoint:port/database
  DATABASE_URL: "postgresql://afrimart:N15ssc2002!@terraform-20260120112103797900000001.cofy448g00lf.us-east-1.rds.amazonaws.com:5432/afrimart"
  
  # Redis connection
  # Format: redis://endpoint:port
  REDIS_URL: "redis://afrimart-staging-redis.3g76r9.0001.use1.cache.amazonaws.com:6379"
  
  # JWT Secret
  JWT_SECRET: "7190117a-61ec-4868-aa94-3a5b8581ceaf"
  
  # SMTP Settings ( for email notifications)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "15cryptt@gmail.com"
  SMTP_PASS: "N15ssc2002!"
